[package]
name = "hello-world-tonic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
prost = "0.12.4"
env_logger = "0.11.3"
tokio = { version = "1.37", features = ["macros", "rt-multi-thread"] }
tonic = "0.11.0"
tonic-build = "0.11.0"

[build-dependencies]
tonic-build = "0.11"